apiVersion: a2a.dev/v1
kind: Agent
metadata:
  name: coder
  description: "A coder agent for feature development and code reviews"
  version: "0.1.0"
spec:
  capabilities:
    streaming: true
    pushNotifications: true
    stateTransitionHistory: true
  agent:
    provider: deepseek
    model: deepseek-chat
    systemPrompt: |
      You are an expert coding assistant specialized in software development, code reviews, debugging, and refactoring.
      You help developers write clean, efficient, and maintainable code across multiple programming languages.
      You can analyze code, suggest improvements, fix bugs, implement features, and provide technical guidance.
    maxTokens: 8192
    temperature: 0.1
  tools:
    - name: read_file
      description: "Read the contents of a file"
      schema:
        type: object
        properties:
          path:
            type: string
            description: "The file path"
          limit:
            type: integer
            description: "The count of lines to read"
            maximum: 1000
        required:
          - path
    - name: write_file
      description: "Write or create a file with given content"
      schema:
        type: object
        properties:
          path:
            type: string
            description: "The file path"
          content:
            type: string
            description: "The content to write to the file"
          mode:
            type: string
            description: "Write mode: 'write' (overwrite) or 'append'"
            enum:
              - "write"
              - "append"
            default: "write"
        required:
          - path
          - content
    - name: list_directory
      description: "List contents of a directory"
      schema:
        type: object
        properties:
          path:
            type: string
            description: "The directory path"
          recursive:
            type: boolean
            description: "Whether to list recursively"
            default: false
        required:
          - path
    - name: search_code
      description: "Search for code patterns or text in files"
      schema:
        type: object
        properties:
          query:
            type: string
            description: "The search query or pattern"
          path:
            type: string
            description: "The directory or file path to search in"
          file_pattern:
            type: string
            description: "File pattern to match (e.g., '*.py', '*.js')"
          case_sensitive:
            type: boolean
            description: "Whether the search is case sensitive"
            default: false
        required:
          - query
          - path
    - name: execute_command
      description: "Execute a shell command"
      schema:
        type: object
        properties:
          command:
            type: string
            description: "The command to execute"
          working_directory:
            type: string
            description: "The working directory for the command"
          timeout:
            type: integer
            description: "Command timeout in seconds"
            default: 30
        required: [command]
    - name: git_operations
      description: "Perform git operations like status, diff, commit, etc."
      schema:
        type: object
        properties:
          operation:
            type: string
            description: "The git operation to perform"
            enum: 
              - "clone"
              - "status"
              - "diff"
              - "add"
              - "commit"
              - "push"
              - "pull"
              - "checkout"
              - "branch"
          args:
            type: array
            items:
              type: string
            description: "Additional arguments for the git command"
          message:
            type: string
            description: "Commit message (required for commit operation)"
        required:
          - operation
  server:
    port: 8443
    debug: false
    auth:
      enabled: true

  language:
    go:
      module: "github.com/inference-gateway/coder-agent"
      version: "1.24"
