# Generated by A2A CLI v0.4.3 at 2025-07-23 22:26:14 UTC. DO NOT EDIT.
# This file was automatically generated from an Agent Definition Language (ADL) file.
# To regenerate this file, run: a2a generate
#
# For more information about A2A CLI, visit: https://github.com/inference-gateway/a2a-cli

FROM golang:1.22-alpine AS builder

WORKDIR /app

# Install ca-certificates for HTTPS requests
RUN apk --no-cache add ca-certificates

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Final stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates tzdata

WORKDIR /root/

# Copy the binary from builder stage
COPY --from=builder /app/main .

# Copy agent card
COPY --from=builder /app/.well-known ./.well-known

# Expose port
EXPOSE 8443

# Set environment variables
ENV A2A_SERVER_PORT=8443
ENV A2A_SERVER_HOST=0.0.0.0

# Run the application
CMD ["./main"]
